### ISSUE TITLE
Fatal Error: Invalid Time value

### ISSUE THREAD

**Issue by lenonay** [lenonay/ip-blocker#1]
En algún punto Juzgando las peticiones falla un `Date.ToISOString`. El error está en la clase DBJudge. Concretamente en el método **JudgeBehavior**. Este es el error que arroja node

Error: RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at DBJudge.JudgeBehavior (file:///home/nonay/ip-blocker/models/DBJudge.js:140:69)
    at JudgeBehavior (file:///home/nonay/ip-blocker/controllers/judge.js:18:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/nonay/ip-blocker/blocker.js:33:5

**Comment by lenonay** [comment]
Ahora se guarda la fecha directamente como sale del objeto **Date()**. Evitando confusión y problemas de compatibilidad
